# Point of reference for the location of the bounding box. The point of reference is always the center of the bounding
# box’s bottom surface (at height = 0) and is described in coordinates of the AGV’s coordinate system.

float64 x     # x-coordinate of the point of reference.
float64 y     # y-coordinate of the point of reference.
float64 z     # z-coordinate of the point of reference.
float64 theta # Orientation of the loads bounding box. Important for tugger trains etc
