float64 speed_min           # Minimal controlled continuous speed of the AGV [m/s]

float64 speed_max           # Maximum speed of the AGV [m/s]

float64 acceleration_max    # Maximum acceleration with maximum load [m/s^2]

float64 deceleration_max    # Maximum deceleration with maximum load [m/s^2]

float64 height_min          # Minimum height of the AGV [m]

float64 height_max          # Maximum height of the AGV [m]

float64 width               # Width of the AGV [m]

float64 length              # Length of the AGV [m]